export enum ProposalStatus {
  RECEIVED = 'RECEIVED',
  OFFER_VALIDATED = 'OFFER_VALIDATED',
  BENEFITS_VALIDATED = 'BENEFITS_VALIDATED',
  SUBMITTED = 'SUBMITTED',
  CARD_ACCOUNT_CREATED = 'CARD_ACCOUNT_CREATED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}
